name: flutter_html_latex
description: "LaTeX support for flutter_widget_from_html_core via math-tex HTML class rendering."
repository: https://github.com/avijitbarua/flutter_html_latex.git
version: 0.1.1
license: MIT
publish_to: none

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ^0.17.0
  flutter_math_fork:
    git:
      url: https://github.com/moon-book/flutter_math_fork
      ref: main
  flutter_tex: #^5.2.6
    git:
      url: https://github.com/moon-book/flutter_tex
      ref: main



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:


topics:
- flutter
- html
- latex
- math
- flutter-widget
platforms:
  android:
  ios:
  web:
